apiVersion: stash.appscode.com/v1beta1
kind: BackupConfiguration
metadata:
    name: ${BACKUP_PROFILE_NAME}
spec:
    repository:
        name: ${BACKUP_REPO_NAME}
    schedule: "${BACKUP_SCHEDULE}"
    target:
        ref:
            apiVersion: apps/v1
            kind: Deployment
            name: ${BACKUP_DEPLOYMENT_NAME}
        paths:
        - ${BACKUP_DATA_FOLDER_PATH}
        volumeMounts:
        - name: ${BACKUP_DATA_VOLUME_NAME}
          mountPath: ${BACKUP_DATA_FOLDER_PATH}
    runtimeSettings:
        container:
            securityContext: ${BACKUP_SECURITY_CONTEXT}
    retentionPolicy: ${BACKUP_RETENTION_POLICY}
    # It is not started by default because maybe we want to start with
    # a restore operation
    paused: true
