apiVersion: stash.appscode.com/v1alpha1
kind: Repository
metadata:
    name: ${BACKUP_REPO_NAME}
spec:
    backend:
        s3:
            endpoint: ${BACKUP_S3_ENDPOINT}
            region: ${BACKUP_S3_REGION}
            bucket: ${BACKUP_REPO_BUCKET_NAME}
            prefix: ${BACKUP_REPO_PREFIX}
        storageSecretName: ${BACKUP_REPO_SECRET_NAME}