apiVersion: stash.appscode.com/v1beta1
kind: BackupConfiguration
metadata:
    name: ${BACKUP_PROFILE_NAME}
spec:
    schedule: "${BACKUP_SCHEDULE}"
    driver: VolumeSnapshotter
    target:
        ref:
            apiVersion: v1
            kind: PersistentVolumeClaim
            name: ${BACKUP_PVC_NAME}
        snapshotClassName: ${BACKUP_SNAPSHOT_CLASS}
    retentionPolicy: ${BACKUP_RETENTION_POLICY}
    # It is not started by default because maybe we want to start with
    # a restore operation
    paused: true
