apiVersion: v1
kind: ConfigMap
metadata:
    name: fip-controller-config
    namespace: fip-controller
data:
    config.json: |
        {
          "hcloud_floating_ips": [ "${HETZNER_FLOATING_IP}" ],
          "node_address_type": "external"
        }
---
apiVersion: v1
kind: Secret
metadata:
    name: fip-controller-secrets
    namespace: fip-controller
stringData:
    HCLOUD_API_TOKEN: ${HETZNER_CLOUD_TOKEN}
